-- SCHATZSUCHE ONLINE V6.8
-- Performance-Helfer, Chat, öffentliche Profile, Kartenanalyse, Standard-Zugzeit
-- Nach V6.7 EINMAL vollständig im Supabase SQL Editor ausführen.

-- 1) Zentrale Standard-Zugregeneration für neu erstellte Spiele
alter table public.platform_settings
  add column if not exists default_regen_seconds int not null default 5;

update public.platform_settings
set default_regen_seconds=5
where id=1 and default_regen_seconds is distinct from 5;

-- 2) Öffentliche Spielerprofile: nur die ausdrücklich öffentlichen Felder zurückgeben.
create or replace function public.get_public_profile_v68(p_user_id uuid)
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
 select case when p.id is null then null else jsonb_build_object(
   'id',p.id,
   'display_name',p.display_name,
   'bio',coalesce(p.bio,''),
   'avatar_path',p.avatar_path,
   'wins',p.wins,
   'total_games',p.total_games,
   'total_fields_revealed',p.total_fields_revealed,
   'gold_found_ug',p.gold_found_ug
 ) end
 from (select 1) x
 left join public.profiles p on p.id=p_user_id
 where auth.uid() is not null;
$$;
revoke all on function public.get_public_profile_v68(uuid) from public;
grant execute on function public.get_public_profile_v68(uuid) to authenticated;

-- 3) Spielchat
create table if not exists public.game_messages(
 id bigint generated by default as identity primary key,
 game_id uuid not null references public.games(id) on delete cascade,
 user_id uuid not null references public.profiles(id) on delete cascade,
 display_name text not null,
 message text not null check(char_length(message) between 1 and 500),
 created_at timestamptz not null default now()
);
create index if not exists game_messages_game_created_idx on public.game_messages(game_id,created_at desc);
alter table public.game_messages enable row level security;

drop policy if exists "v68 game chat member read" on public.game_messages;
create policy "v68 game chat member read" on public.game_messages
for select to authenticated
using(exists(select 1 from public.game_players gp where gp.game_id=game_messages.game_id and gp.user_id=auth.uid()));

-- Direkte INSERTs bleiben verboten; Schreiben nur über RPC.
create or replace function public.send_game_message_v68(p_game_id uuid,p_message text)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  mid bigint;
  clean text:=trim(coalesce(p_message,''));
  n text;
begin
 if auth.uid() is null then raise exception 'Nicht angemeldet'; end if;
 if not exists(select 1 from game_players where game_id=p_game_id and user_id=auth.uid()) then
   raise exception 'Nur Spielteilnehmer können schreiben';
 end if;
 if char_length(clean)<1 or char_length(clean)>500 then raise exception 'Nachricht muss 1 bis 500 Zeichen haben'; end if;
 select display_name into n from profiles where id=auth.uid();
 insert into game_messages(game_id,user_id,display_name,message)
 values(p_game_id,auth.uid(),coalesce(n,'Spieler'),clean)
 returning id into mid;
 return mid;
end;
$$;
revoke all on function public.send_game_message_v68(uuid,text) from public;
grant execute on function public.send_game_message_v68(uuid,text) to authenticated;

-- Realtime-Publikation, wenn noch nicht vorhanden.
do $$
begin
 if not exists(
  select 1 from pg_publication_tables
  where pubname='supabase_realtime' and schemaname='public' and tablename='game_messages'
 ) then
  alter publication supabase_realtime add table public.game_messages;
 end if;
exception when others then
 raise notice 'Realtime publication konnte nicht automatisch ergänzt werden: %',sqlerrm;
end $$;

-- 4) Kartenbasierte Analyse.
-- Ergebnis ist absichtlich nur ein grober geografischer Bereich, nie die exakte Schatzkoordinate.
create or replace function public.get_analysis_hint_v68(p_game_id uuid,p_x int,p_y int)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
 g games%rowtype;
 gp game_players%rowtype;
 tx int; ty int;
 target_lat numeric; target_lon numeric;
 click_lat numeric; click_lon numeric;
 meters_lon numeric;
 bucket_m numeric;
 lat_step numeric; lon_step numeric;
 approx_lat numeric; approx_lon numeric;
 dx numeric; dy numeric; dist_m numeric;
 direction text;
 gt record;
begin
 if auth.uid() is null then raise exception 'Nicht angemeldet'; end if;
 select * into g from games where id=p_game_id;
 if not found then return null; end if;
 select * into gp from game_players where game_id=p_game_id and user_id=auth.uid();
 if not found or gp.analysis_level<=0 then return null; end if;

 if g.game_type='pay' then
   select x,y into gt from gold_treasures where game_id=p_game_id and found_by is null order by treasure_no limit 1;
   if not found then return null; end if;
   tx:=gt.x;ty:=gt.y;
 else
   tx:=g.treasure_x;ty:=g.treasure_y;
 end if;

 meters_lon:=greatest(1000,111320*cos(radians(g.center_lat)));
 target_lat:=g.center_lat + ((g.height/2.0)-(ty+0.5))*g.cell_size_m/111320.0;
 target_lon:=g.center_lon + ((tx+0.5)-(g.width/2.0))*g.cell_size_m/meters_lon;
 click_lat:=g.center_lat + ((g.height/2.0)-(p_y+0.5))*g.cell_size_m/111320.0;
 click_lon:=g.center_lon + ((p_x+0.5)-(g.width/2.0))*g.cell_size_m/meters_lon;

 bucket_m:=case gp.analysis_level
   when 1 then greatest(5000,g.cell_size_m*80)
   when 2 then greatest(2500,g.cell_size_m*40)
   when 3 then greatest(1200,g.cell_size_m*20)
   when 4 then greatest(600,g.cell_size_m*10)
   when 5 then greatest(300,g.cell_size_m*5)
   else greatest(150,g.cell_size_m*2)
 end;
 lat_step:=bucket_m/111320.0;
 lon_step:=bucket_m/meters_lon;
 approx_lat:=round(target_lat/lat_step)*lat_step;
 approx_lon:=round(target_lon/lon_step)*lon_step;

 dx:=(target_lon-click_lon)*meters_lon;
 dy:=(target_lat-click_lat)*111320.0;
 dist_m:=sqrt(dx*dx+dy*dy);
 direction:=case
   when abs(dx)<dist_m*.25 and dy>0 then 'Norden'
   when abs(dx)<dist_m*.25 and dy<0 then 'Süden'
   when abs(dy)<dist_m*.25 and dx>0 then 'Osten'
   when abs(dy)<dist_m*.25 and dx<0 then 'Westen'
   when dx>0 and dy>0 then 'Nordosten'
   when dx<0 and dy>0 then 'Nordwesten'
   when dx>0 and dy<0 then 'Südosten'
   else 'Südwesten' end;

 return jsonb_build_object(
  'level',gp.analysis_level,
  'lat',round(approx_lat,6),
  'lon',round(approx_lon,6),
  'radius_m',bucket_m,
  'text',case
    when gp.analysis_level=1 then 'Der Schatz liegt grob '||direction||' von deiner letzten Suche. Orientiere dich an den großen Orten und Landschaftsmerkmalen im markierten Kartenbereich.'
    when gp.analysis_level=2 then 'Suche '||direction||'. Der relevante Kartenbereich ist ungefähr '||round(bucket_m/1000.0,1)||' km groß. Nutze Orte, Straßen und Gewässer als Orientierung.'
    when gp.analysis_level=3 then 'Der Schatz befindet sich '||direction||' deiner letzten Suche, ungefähr '||round(dist_m/100.0)*100||' m entfernt. Der markierte Bereich grenzt die passende Landschaft ein.'
    when gp.analysis_level=4 then 'Kartenradar: etwa '||round(dist_m/100.0)*100||' m Richtung '||direction||'. Vergleiche den gelben Suchbereich mit Straßen, Wegen, Orten und Gewässern.'
    when gp.analysis_level=5 then 'Geodatenanalyse: ungefähr '||round(dist_m/50.0)*50||' m Richtung '||direction||'. Der Kartenbereich ist jetzt deutlich enger.'
    else 'KI-Kartenanalyse: ungefähr '||round(dist_m/25.0)*25||' m Richtung '||direction||'. Suche innerhalb des kleinen markierten realen Kartenbereichs.' end
 );
end;
$$;
revoke all on function public.get_analysis_hint_v68(uuid,int,int) from public;
grant execute on function public.get_analysis_hint_v68(uuid,int,int) to authenticated;

-- 5) V6.7-Schaltzentrale um Standard-Zugzeit ergänzen.
-- Die existierende Admin-RPC bekommt den Wert aus dem JSON, falls vorhanden.
create or replace function public.admin_set_default_regen_v68(p_seconds int)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
 if not public.is_admin_v67() then raise exception 'Keine Admin-Berechtigung'; end if;
 if p_seconds<1 or p_seconds>86400 then raise exception 'Ungültige Standard-Zugzeit'; end if;
 update platform_settings set default_regen_seconds=p_seconds,updated_at=now() where id=1;
end;
$$;
revoke all on function public.admin_set_default_regen_v68(int) from public;
grant execute on function public.admin_set_default_regen_v68(int) to authenticated;
